# Generated by Django 2.2.13 on 2020-09-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.SmallIntegerField(),
        ),
    ]
